Repository larsk21/compiler-minijava, pull requests merged in 2022-02, with the labels that each got.

#153 Add `MinimizeRegisterPressure` strategy to `LoopInvariantOptimization`
  src/main/java/edu/kit/compiler/optimizations/LinearBlocksOptimization.java
  src/main/java/edu/kit/compiler/optimizations/LoopInvariantOptimization.java
  src/main/java/edu/kit/compiler/optimizations/NodeCosts.java
  src/main/java/edu/kit/compiler/optimizations/Util.java
  src/main/java/edu/kit/compiler/optimizations/loop_invariant/MoveInvariantStrategies.java
  src/test/java/edu/kit/compiler/optimizations/LoopInvariantOptimizationCallTest.java
  src/test/java/edu/kit/compiler/optimizations/LoopInvariantOptimizationTest.java
Labels: bug, enhancement

#146 Add loop unrolling optimization
  mjtest-files/exec/unroller/DeepNesting.java
  mjtest-files/exec/unroller/Misc.java
  mjtest-files/exec/unroller/NonConstBounds.0.inputc
  mjtest-files/exec/unroller/NonConstBounds.0.inputc.out
  mjtest-files/exec/unroller/NonConstBounds.input.java
  mjtest-files/exec/unroller/Vec3.java
  src/main/java/edu/kit/compiler/JavaEasyCompiler.java
  src/main/java/edu/kit/compiler/optimizations/ArithmeticIdentitiesOptimization.java
  src/main/java/edu/kit/compiler/optimizations/Util.java
  src/main/java/edu/kit/compiler/optimizations/unrolling/LoopAnalysis.java
  src/main/java/edu/kit/compiler/optimizations/unrolling/LoopUnroller.java
  src/main/java/edu/kit/compiler/optimizations/unrolling/LoopUnrollingOptimization.java
  src/main/java/edu/kit/compiler/optimizations/unrolling/LoopVariableAnalysis.java
  src/test/java/edu/kit/compiler/optimizations/LoopUnrollingTest.java
Labels: enhancement

#154 Adjust inlining heuristic
  src/main/java/edu/kit/compiler/optimizations/inlining/InliningOptimization.java
  src/main/java/edu/kit/compiler/optimizations/inlining/InliningStateTracker.java
Labels: enhancement

#156 fix: Loop variable analysis
  mjtest-files/exec/unroller/NonConstStep.0.inputc
  mjtest-files/exec/unroller/NonConstStep.0.inputc.out
  mjtest-files/exec/unroller/NonConstStep.input.java
  src/main/java/edu/kit/compiler/optimizations/unrolling/LoopVariableAnalysis.java
Labels: bug

#159 fix: Bugs relating to const functions
  mjtest-files/exec/inliner/LargeConstFunction.0.inputc
  mjtest-files/exec/inliner/LargeConstFunction.0.inputc.out
  mjtest-files/exec/inliner/LargeConstFunction.input.java
  src/main/java/edu/kit/compiler/optimizations/attributes/AttributeAnalysis.java
  src/main/java/edu/kit/compiler/optimizations/attributes/Attributes.java
  src/main/java/edu/kit/compiler/optimizations/inlining/Inliner.java
Labels: bug

#161 Fix a bug in the `PureFunctionOptimization`
  src/main/java/edu/kit/compiler/optimizations/PureFunctionOptimization.java
Labels: bug

#160 Improve handling of Phis in loop variable analysis
  mjtest-files/exec/unroller/MultiplePhis.java
  src/main/java/edu/kit/compiler/optimizations/unrolling/LoopVariableAnalysis.java
Labels: bug, enhancement

#162 Fix nasty bug in register allocation/lifetime analysis
  run_mjtests.sh
  src/main/java/edu/kit/compiler/register_allocation/ApplyAssignment.java
  src/main/java/edu/kit/compiler/register_allocation/LifetimeAnalysis.java
Labels: bug

#163 Do not move loop invariant `Cmp` nodes
  src/main/java/edu/kit/compiler/optimizations/analysis/LoopInvariantAnalysis.java
  src/test/java/edu/kit/compiler/optimizations/LoopInvariantOptimizationTest.java
Labels: enhancement

#167 Fix a regression in the pure function optimization
  mjtest-files/exec/PureFunctionTerminates.inf.java
  src/main/java/edu/kit/compiler/optimizations/PureFunctionOptimization.java
Labels: bug

#168 make access to definition type safer in detailed type analysis
  mjtest-files/semantic/UnresolvedClass.invalid.java
  src/main/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitor.java
Labels: bug, enhancement

#164 Fix issues related to loop unrolling
  mjtest-files/exec/PureFunctionTerminates.inf.java
  mjtest-files/exec/unroller/HeaderPhiConst.java
  mjtest-files/exec/unroller/PrematureReturn.java
  mjtest-files/exec/unroller/UnclosedLoop.java
  src/main/java/edu/kit/compiler/optimizations/PureFunctionOptimization.java
  src/main/java/edu/kit/compiler/optimizations/unrolling/LoopAnalysis.java
  src/main/java/edu/kit/compiler/optimizations/unrolling/LoopUnroller.java
  src/main/java/edu/kit/compiler/optimizations/unrolling/LoopUnrollingOptimization.java
  src/main/java/edu/kit/compiler/optimizations/unrolling/LoopVariableAnalysis.java
Labels: bug

#171 Fix endless recursion in unused args analysis
  mjtest-files/exec/unusedArgs/AlphabeticalRegisterTransfer.java
  src/main/java/edu/kit/compiler/optimizations/analysis/UnusedArgumentsAnalysis.java
Labels: bug

#155 Update readme
  readme.md
  src/main/java/edu/kit/compiler/JavaEasyCompiler.java
Labels: enhancement

#173 Fix for target size in case of upcast to stack slot
  mjtest-files/compile/RegAllocUpcastSize.mj
  src/main/java/edu/kit/compiler/register_allocation/ApplyAssignment.java
Labels: bug

#172 Add some debug improvements
  readme.md
  src/main/java/edu/kit/compiler/DebugFlags.java
  src/main/java/edu/kit/compiler/JavaEasyCompiler.java
  src/main/java/edu/kit/compiler/cli/Cli.java
  src/main/java/edu/kit/compiler/io/CommonUtil.java
  src/main/java/edu/kit/compiler/parser/PrintAstVisitor.java
Labels: enhancement
